22. Create an array $y = \begin{pmatrix}3 & 5 & 3\\2 & 2 & 5 \\3 & 8 & 9\end{pmatrix}$ and calculate its transpose.

In [1]:
import numpy as np 

Y = np.array([[3,5,3],[2,2,5],[3,8,9]])

transY = np.transpose(Y)

print("The Transposed array is: ")
print(transY)

The Transposed array is: 
[[3 2 3]
 [5 2 8]
 [3 5 9]]


24. Create a 2 × 4 zero array

In [2]:
import numpy as np

zeros = [[1] * 2 for _ in range(4)]

print(zeros)

[[1, 1], [1, 1], [1, 1], [1, 1]]


In [10]:
import math
from turtle import *


def hearta(k):
    return 15*math.sin(k)**3


def heartb(k):
    return 12*math.cos(k)-5 *\
        math.cos(2*k)-2 *\
        math.cos(3*k) -\
        math.cos(4*k)


speed(0)
bgcolor("black")
for i in range(10000):
    goto(hearta(i)*20, heartb(i)*20)
    for j in range(5):
        color("#0096FF")
    goto(0, 0)
done()


Terminator: 